### PR TITLE
New build log markup and CSS.

### LINKED ISSUE #527: Tweaks to the builds page
It's looking great but there's a couple of tweaks that would make it better.

* If any of the branch/tag builds are not valid (specifically the beta tag) let's exclude it. For example [Rester has no beta > the stable right now](https://staging.swiftpackageindex.com/finestructure/Rester/builds) so let's not show it.
* If a package has no builds for a tag, let's put a message saying "No builds available." in a `<p>` tag instead of the `<ul>`.

### LINKED ISSUE #536: Add better visualisation of build logs
Currently the whole log is shown in a single `pre`/`code` block. The important data is usually at the bottom of the log, which means there's a lot of scrolling every time you view a log.

To fix this:

* Display the logs inside a `pre`/`code` section inside a new `div` that has an explicit height, so that the log scrolls inside the `div.
* Scroll that `div` to the bottom of the page on page load.

### PR DESCRIPTION
**Pull request by daveverwer**
OK, this needs quite a bit of wiring up work to be ready for merging, I’m out of time for this weekend, but I’m going to summarise what needs doing.

We should be able to leave out any parts of this that don’t get wired up by just commenting out the HTML for that section, but  I thought I’d produce the markup/styling for as much as possible.

### In the builds/index view:

- [x] Wire up the total number of builds
- [x] Link back to the package page in the opening paragraph.
- [x] Wire up the build statuses
- [x] Wire up individual build log links into the new matrix format.
- [x] Remove old builds list.

### In the builds/show view:

- [x] Wire up the View all builds link.
- [x] Wire up the package name
- [x] Link back to the package page in the opening paragraph.
- [x] Wire up the Swift version, platform version, and Xcode version (see comment in the source about the Xcode version).
- [ ] Wire up the build command (dependent on #557).

### Before merging
- [x] Remove XCTSkip from `WebpageSnapshotTests.setUpWithError`
- [x] Update snapshots

Fixes #527
Fixes #536

---

Screenshot 2020-07-26 at 11 53 46@2x

Screenshot 2020-07-26 at 11 54 00@2x

### CODE REVIEW

**Comment by daveverwer** [comment]
Dark mode colours aren't in yet either, if we go ahead with this it's easy to add them though.

**Comment by daveverwer** [comment]
Feel pretty good about this design after thinking on it for a few hours.

I fixed a couple of bugs with it, added the "unknown" state for missing builds and gave it dark mode compatibility.

Screenshot 2020-07-25 at 22 07 06
Screenshot 2020-07-25 at 22 06 34

**Comment by daveverwer** [comment]
Works great on mobile too:

Screenshot 2020-07-25 at 22 10 44@2x

**Comment by daveverwer** [comment]
It works well when there are only two columns too:

Screenshot 2020-07-25 at 22 13 33@2x
Screenshot 2020-07-25 at 22 13 48@2x

**Comment by finestructure** [comment]
Not sure if it’s GH or my connection but none of the images are loading for me!

**Comment by daveverwer** [comment]
They seem ok here. I thinking might be your connection

**Comment by finestructure** [comment]
I’m almost done with the index view. Still need to wire up the build log links and we should look into how we’re going to deal with the long row headers:

Screenshot 2020-07-28 at 16 29 36

**Comment by finestructure** [comment]
We’re repeating Swift a lot, so perhaps we could trim this to:

```
5.3 | iOS
5.3 | macOS (xcode)
5.3 | macOS (SPM)
5.3 | macOS (xcode, ARM)
…
```

**Comment by daveverwer** [comment]
Or, we could have multiple matrix `ul` lists and have a `h3` splitting them up with the Swift version.

That'd do two things. It'd help with the row headings, and also break the page up a bit.

**Comment by finestructure** [comment]
Screenshot 2020-07-28 at 16 41 17

**Comment by finestructure** [comment]
For my sanity, I’d vote to just go with shorter labels for now 🤣

**Comment by finestructure** [comment]
We should probably also display the build status on the detail page, perhaps similar to the license lozenge in the top right or something.

**Pull request merged**
