### PR TITLE
Add a last activity filter

### LINKED ISSUE #1303: Add more metadata to package lists
Having the number of stars showing against a package is something, but as I [mentioned here](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1163#issuecomment-887329608), it's super reductive.

There's a whole load of metadata about a package that can inform which search result or package in a keyword/author view to click on. Until we have a "quality index" style system for packages that would reduce the metadata into one or two scores, we should pull out more information so that decisions are not _only_ based on stars.

Initially, I'd like to add one more field. It should be something along the lines of "last active", which could reduce several dates we have into one which sums up how recently a package has received maintenance.

So, if there has been a commit on the default branch, a release, or some activity from one of the maintainers (not just a new issue being opened, but something that required the maintainer to do something), then we should show something like:

```
owner/package – Active X months/weeks/days ago – 345 stars
```

Something like this:

Screenshot 2021-10-19 at 15 03 07@2x

### PR DESCRIPTION
**Pull request by daveverwer**
Merge after #1389
Fixes #1303 

I can see an argument to have both of these available, but I think until the feature is finished we should keep things simple. Changing this from last commit to last activity as I think that's a more useful filter parameter.

### CODE REVIEW

**Comment by Sherlouk** [comment]
Is there any reason to not support both?

Correct me if I'm wrong but last activity could include somebody other than the author creating a new issue or something - it doesn't necessary mean the project is actively being maintained? At least commit means code is actually changing - though a very crude measure of quality.

**Comment by Sherlouk** [comment]
(This ticket also reminds me that filters still only work in staging 😭  - I should come back and finish up the UI for it)

**Comment by daveverwer** [comment]
> Is there any reason to not support both?

Yea. As I mentioned there's an argument to have both but this feature is in a funny place as it never quite made it out of the door. If I had to pick between the two, I'd say last commit/issue/pr activity is better than *purely* last commit and I'm reluctant expand the scope of the feature (which then needs maintaining) before it's finished.

> Correct me if I'm wrong but last activity could include somebody other than the author creating a new issue or something - it doesn't necessary mean the project is actively being maintained? At least commit means code is actually changing - though a very crude measure of quality.

Not quite. Creating an issue wouldn't count as activity. Closing or merging a pull request, closing an issue, or committing code is what counts as activity. I'd class all of those as active maintenance.

**Comment by daveverwer** [comment]
> (This ticket also reminds me that filters still only work in staging 😭 - I should come back and finish up the UI for it)

I would very much support that! It's so close to being a fantastic feature.

**Comment by Sherlouk** [comment]
> As I mentioned

Yeah turns out I didn't read your message in the slightest, sorry 😂 

> Creating an issue wouldn't count as activity. Closing or merging a pull request, closing an issue, or committing code is what counts as activity

What if I create a ticket on your repo, and then close it myself?

**Comment by daveverwer** [comment]
> What if I create a ticket on your repo, and then close it myself?

That would need testing. I have a feeling that it would count as activity, though.

**Comment by Sherlouk** [comment]
> I have a feeling that it would count as activity

Good to know at least. A point for a future issue but when we add UI for this it'd be good to add a definition of "activity" somewhere so users know.

Happy with the code 👍

**Comment by daveverwer** [comment]
Note: Move `viewDateFormatter` from #1401 out into a global helper as part of this.

**Comment by daveverwer** [comment]
Superseded by #1406

**Pull request closed without merging**
