### PR TITLE
Doc route 2

### PR DESCRIPTION
**Pull request by finestructure**
Bring back the DocRoute changes.

~~⚠️ This is the crashing version. Do not merge unless the fix is merged into this branch. ⚠️~~

Edit: the fix has been merged into this branch. It's good to go now.

### CODE REVIEW

**Comment by finestructure** [comment]
This is now ready for review and merge and we should finally be able to move forward with the canonical document changes.

**Comment by finestructure** [comment]
There's a decent chance that this was the culprit: https://github.com/vapor/routing-kit/pull/130

I'll retest the crashing version with the upstream change once it's released.

**Comment by finestructure** [comment]
The crashing version still crashes despite the routing-kit fix. (In hindsight, that fix was unlikely to be the root cause anyway.)

**Review by daveverwer — APPROVED** [review]

**Comment by finestructure** [comment]
Deployed as 2.103.0. Looking good, no crashes:

CleanShot 2024-05-06 at 13 56 13@2x

**Pull request merged**
