### PR TITLE
Set AASA content type

### LINKED ISSUE #1035: Universal Links not working
The AASA file is serving correctly, but it does not open the app 😬

https://staging.swiftpackageindex.com/.well-known/apple-app-site-association

### PR DESCRIPTION
**Pull request by finestructure**
Fixes #1035 

Before:
```
❯ curl -D - http://localhost:8080/.well-known/apple-app-site-association
HTTP/1.1 200 OK
etag: 1618546949.8858228-403
content-length: 403
connection: keep-alive
date: Fri, 16 Apr 2021 05:22:43 GMT
```

After:
```
❯ curl -D - http://localhost:8080/.well-known/apple-app-site-association
HTTP/1.1 200 OK
etag: 1618550676.2519999-403
content-length: 403
content-type: application/json
connection: keep-alive
date: Fri, 16 Apr 2021 05:27:50 GMT
```

### CODE REVIEW

**Comment by finestructure** [comment]
Setting to draft, we'll want a test to ensure this isn't broken.

**Comment by finestructure** [comment]
I'll deploy from branch to test before merge.

**Comment by finestructure** [comment]
Mmm, that breaks css for some reason:

CleanShot 2021-04-16 at 08 24 11@2x

**Comment by finestructure** [comment]
But only on actual staging - if I run this locally it's all fine. I wonder if we had a bad build there.

**Comment by daveverwer** [comment]
Yea I can't see why this would break the CSS 😅

**Review by daveverwer — COMMENTED** [review]
I can't comment on the diff as it's a file rename that I'd like to comment on, so I'll leave a general comment. Now that the file is being served not related to its filename, we could rename the file in `Resources` to have a `.json` extension, which would (for me at least) give syntax highlighting and validation when editing it. I had to keep renaming it and then removing the extension when working on the file, which was annoying.

**Comment by finestructure** [comment]
Works after rebuild and redeploy.

**Comment by daveverwer** [comment]
Just pushed that rename change too.

**Review by daveverwer — APPROVED** [review]

**Pull request merged**
