### PR TITLE
Remove intel builds

### LINKED ISSUE #1655: Stop triggering macOS (Intel) builds

### LINKED ISSUE #1656: Remove visualisation of macOS (Intel) builds

### PR DESCRIPTION
**Pull request by finestructure**
This removes display and triggering of Intel builds - by removing the ARM builds. We'll re-interpret `macosSpm` and `macosXcodebuild` to trigger these as arm64 builds on the builder side. I.e. for all intents and purposes the server simple requests and receives macOS builds of the two kinds (SPM and xcodebuild) and lets the builder decide how to actually build them.

Fixes #1655 
Fixes #1656 

Deployment:

- [x] prepare builder PR to remove `macosSpm` + `macosXcodebuild` platform cases
- [x] [deploy builder](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/104) to re-interpret `macosSpm` + `macosXcodebuild` triggers
- [ ] merge this PR
- [ ] deploy this PR
- [x] delete arm builds from the db in order to make build selection counts align (part of this PR now)
- [ ] [deploy builder](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/103) to remove `macosSpm` + `macosXcodebuild` platform cases

### CODE REVIEW

**Comment by daveverwer** [comment]
There's almost certainly some CSS we can remove along with this, I'll check it out and fix that up.

**Comment by finestructure** [comment]
Interesting, this has triggered a Query Performance Test failure (re-run failed as well). Re-testing on `main` to see if it's a real regression.

**Comment by finestructure** [comment]
Fails on `main` as well now. Must be staging's db having degraded performance. The load is flat:

CleanShot 2022-04-05 at 14 22 51@2x

Maybe it's latency?

Probably a good idea to set the perf test to allow to fail.

**Comment by daveverwer** [comment]
> There's almost certainly some CSS we can remove along with this, I'll check it out and fix that up.

I took a good look at this and there's nothing we can do to remove anything from the CSS or markup from this change. We still need to support the format of:

```
Title
Subtitle
```

For the beta versions of Swift ([see here](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/60c0419ae15bf829732672774246c577db51a5eb/Sources/App/Views/PackageController/SwiftVersion%2BBuildResultParameter.swift#L19) for details). So there's nothing to do here on the front-end!

**Review by daveverwer — APPROVED** [review]
I really like that this simplifies things like it does!

**Comment by finestructure** [comment]
Intel/ARM build distinction removed end-to-end across server and builder now.

**Pull request merged**
