### PR TITLE
Removed the word “Compatibility” from the shields.io badges

### LINKED ISSUE #2863: Remove the word "Compatibility" from shields.io badges
### Discussed in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/2862

<div type='discussions-op-text'>

<sup>Originally posted by **mattmassicotte** January 24, 2024</sup>
With visionOS now supported, and (hopefully!) catalyst on the way, many of my package's badges no longer fit on a iPhone mini screen comfortably.

So I got to thinking, is "Platform Compatibility" actually even the best wording? Same goes for "Swift Compatibility". I think there is zero ambiguity by dropping the word "Compatibility" and it would make for a much tidier badge.

"Platforms"
"Swift"

What do you think?</div>

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #2863

I'll ad-hoc deploy this to staging before we merge it so I can double-check it works, but I can't see how even I would make a mistake with this one.

### CODE REVIEW

**Comment by mattmassicotte** [comment]
Are you sure you want this to say “Platform” and not “Platforms”?

**Comment by daveverwer** [comment]
> but I can't see how even I would make a mistake with this one.

> Are you sure you want this to say “Platform” and not “Platforms”?

aaaaaand there it is 😂

**Comment by daveverwer** [comment]
Confirmed working.

Screenshot 2024-01-24 at 14 18 08@2x

**Comment by mattmassicotte** [comment]
I have enjoyed everything about this experience. 10/10 will open bugs again.

**Comment by daveverwer** [comment]
> I have enjoyed everything about this experience. 10/10 will open bugs again.

Please rate us on TrustPilot 😂

**Comment by mattmassicotte** [comment]
> Please rate us on TrustPilot 😂

Don't forget to like and subscribe!

**Review by finestructure — APPROVED** [review]

**Comment by finestructure** [comment]
LinkedIn endorsement to follow 👍

**Comment by daveverwer** [comment]
Deploying as 2.98.4

**Pull request merged**
