### PR TITLE
Package collections are no longer in beta

### PR DESCRIPTION
**Pull request by daveverwer**
For some reason, this needed a full snapshot update. No idea why. I looked hard at the diff with Kaleidoscope's "Difference" mode and couldn't see *any* highlighted areas. 🤷‍♂️

### CODE REVIEW

**Review by finestructure — APPROVED** [review]

**Comment by finestructure** [comment]
Might have been due and OS or the Xcode 13 update 🤷

**Comment by daveverwer** [comment]
> Might have been due and OS or the Xcode 13 update 🤷

I've updated nothing. Still running Xcode 13b5 as the project doesn't compile on RC (error building NIO) and I'm still running Big Sur.

**Comment by finestructure** [comment]
But the package update you pushed last week fixed that, didn't it? I'm running RC and it builds and passes tests :)

https://twitter.com/johannesweiss/status/1440379995164065807

**Comment by daveverwer** [comment]
> But the package update you pushed last week fixed that, didn't it? I'm running RC on BS and it builds and passes tests :)
> 
> https://twitter.com/johannesweiss/status/1440379995164065807

Ah, I pushed a package update but didn't realise that one was fixed! 🚀

**Comment by daveverwer** [comment]
Weird that tests are failing on the server, they run fine locally.

**Pull request merged**
