### PR TITLE
Add totals to the Ready for Swift 6 charts

### PR DESCRIPTION
**Pull request by daveverwer**
Thanks to @mattmassicotte for the feedback that led to this!

Adds new "total" marks that show the total number of packages when hovered.

Screenshot 2024-06-18 at 09 01 14@2x

They are associated with the various plots, so when you remove a plot the total also gets hidden.

Screenshot 2024-06-18 at 09 03 57@2x

Unchecking "Show totals" hides all totals.

Screenshot 2024-06-18 at 09 04 48@2x

This only affects the first chart, the total number of errors needs no totals.

### CODE REVIEW

**Review by finestructure — APPROVED** [review]

**Comment by finestructure** [comment]
I was baffled for a moment why the total is 3396 and not ~7599 until I realised that we're constraining the list to recently updated packages. That's probably worth a note somewhere 🤔

**Comment by daveverwer** [comment]
> I was baffled for a moment why the total is 3396 and not ~7500 until I realised that we're constraining the list to recently updated packages. That's probably worth a note somewhere 🤔

We have this:
Screenshot 2024-06-18 at 09 56 54@2x

**Comment by mattmassicotte** [comment]
Great stuff, thank you so much!

**Comment by mattmassicotte** [comment]
I have a potentially annoying question: why not just have a graph that goes down?

"number of packages with zero data race errors"
"number of packges with data race errors"

I'd also possibly change this to:

"number of packges with Swift 6 errors"

But that's maybe being too pendant 😉

**Comment by daveverwer** [comment]
Has cheesy stock photography taught you nothing @mattmassicotte? Charts are best when they go up and to the right!

image

**Comment by mattmassicotte** [comment]
My understanding is this is only true in the nothern hemisphere...

**Pull request merged**
