### PR TITLE
Redrawn icons!

### PR DESCRIPTION
**Pull request by daveverwer**
Redrawn all from scratch (no stock artwork) so that we can have a consistent line width. I also went with a filled style rather than outline as I thought it'd work better.

Happy to make changes though! Feedback welcome.

Before:

Before

After:

After

### CODE REVIEW

**Comment by daveverwer** [comment]
Personal views on how the redrawn ones came out. I'm happy with the top four icons. The Apple and Swift ones are much less readable, but they were too inconsistent with their weightings without being surrounded by something.

The branch/stable/beta icons will look better when they're in-place in the lozenges.

I might try making the Apple and Swift icons bigger. Will post a screenshot.

**Comment by daveverwer** [comment]
These are too big, they stand out far left of the titles, which is bad 😬 but these two specific icons look better at this size.

Gut feeling says that the'll be fine at the smaller size.

Screenshot 2020-05-18 at 18 19 07@2x

**Comment by daveverwer** [comment]
This is about as good as I can get it in terms of a trade-off between the size of those bottom two icons not extending to the left of the titles, and legibility.

Screenshot 2020-05-18 at 18 26 44@2x

**Comment by finestructure** [comment]
Yes, I think the top four look better this way as well. However, I feel now the release icons lost a bit of weight. I _did_ like the circle style. I wonder if it’d work if we made all of them circle styles? So regardless of their actual density they’d still line up well enough.

Although I wonder if some of the symbols would force the circles to be too big.

But looking at the variants, personally I’d prefer the new top four and then the original releases and platform icons.

**Comment by daveverwer** [comment]
> I feel now the release icons lost a bit of weight. I did like the circle style.

You're absolutely right, that was intentional as they're about to be put inside the lozenges. I just haven't put them inside that markup yet. They'll be [like they are here](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/47#issuecomment-630180904).

> But looking at the variants, personally I’d prefer the new top four and then the original releases and platform icons.

I have one more idea for the language and platform icons, I think a rounded rect might just give them a little something over a plain rect. I'll give it one more try.

**Comment by daveverwer** [comment]
Pushed this version:

Screenshot 2020-05-18 at 22 31 56@2x

**Comment by finestructure** [comment]
Ah of course, they go in the lozenges!

And rounded rect for the platforms - that's 👌

**Pull request merged**
