### PR TITLE
Markdown pages for the FAQ and the Privacy Policy

### LINKED ISSUE #179: Documentation: Write a privacy and cookies policy.

### PR DESCRIPTION
**Pull request by daveverwer**
Also the changes to `SiteURL` to allow anchors.

Fixes #179

### CODE REVIEW

**Comment by finestructure** [comment]
I'm getting a few broken links:

Screenshot 2020-06-06 at 18 31 47

**Comment by finestructure** [comment]
We should embed those images, shouldn't we?

**Comment by daveverwer** [comment]
I'll move the images into our repo, well spotted. I originally had them om Imgur as the GitHub wiki doesn't support hosting images.

**Comment by finestructure** [comment]
Merging now, leaving image fixes for a follow-up

**Pull request merged**
