### PR TITLE
Generic compatibility matrix CSS

### LINKED ISSUE #538: Generic styling for the Swift and platform compatibility matrices
Create a generic markup/styling for both the Swift version and platform compatibility matrices.

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #538

### CODE REVIEW

**Comment by daveverwer** [comment]
OK, so I'm confident that this CSS doesn't break anything on the Package page now.

It *does* break the build status icons on the Build Logs page, but that's OK. I was "borrowing" some of these classes for that, which I shouldn't have been. I'll fix that up when I tackle #536.

**Comment by daveverwer** [comment]
@finestructure The good news here is that none of the Package page PNG snapshots changed after I merged the platform matrix code in 👍

**Comment by daveverwer** [comment]
Ready to go if you're happy with it. Working on the build index page next,.

**Comment by finestructure** [comment]
Looks great, I hope this wasn’t too bad to merge in! I think this worked out really well in the end :)

**Comment by daveverwer** [comment]
The merge wasn't too painful, better than expected.

**Pull request merged**
