### PR TITLE
removes the search logging

### PR DESCRIPTION
**Pull request by heckj**
Removes the search logger from the dev infrastructure. Should improve the query response time for search in particular (at least in Dev) and reduce logging consumption in that environment as well.

### CODE REVIEW

**Review by finestructure — APPROVED** [review]

**Comment by daveverwer** [comment]
This has the old problem of not running the tests because they are not under our repository. It works on other repos I am on, but has never worked here and I don't know how to fix it.

I'll re-make this PR under this repo and cherry pick these commits.

**Comment by heckj** [comment]
Well that's annoying - sorry gents, I didn't mean to make this annoying.

**Comment by daveverwer** [comment]
It was no problem!

**Comment by heckj** [comment]
I had a copy/fork of the repo (heckj/SwiftPackageIndex) from ages ago - was still working from that, but that path I guess is what the tests don't care for. Next time I'll make a branch directly on this org's repo and work from there.

**Pull request closed without merging**
