### PR TITLE
Testing cla-bot

### PR DESCRIPTION
**Pull request by daveverwer**

### CODE REVIEW

**Comment by Sherlouk** [comment]
let me know if you need another test subject 👀

**Comment by daveverwer** [comment]
Thanks, James! Unfortunately I need one who hasn't signed a CLA!

**Comment by finestructure** [comment]
Do we need to/want to disable this for the package list repository? It's showing up there (although it doesn't actually prevent merges - not sure if it would/should for other repos).

https://github.com/SwiftPackageIndex/PackageList/pull/3343

CleanShot 2023-01-10 at 10 26 11@2x

**Comment by daveverwer** [comment]
Yes, this is no good. I don't see anything obvious for "all repositories except ..." in the documentation, so I'll disable it all for now.

The alternative is to manually enable it for every repo apart from PackageList, but that's no good as every time we add someone, we'd need to update *all* repository's allow lists.

**Comment by Sherlouk** [comment]
Is there a way to whitelist the GitHub Actions bot?

**Comment by Sherlouk** [comment]
Equally, we don't use it but there is an ability to specify the account used to create the automated PackageList PRs. We could update it to use an account which has signed the CLA (be it you or Sven)?

Just throwing ideas out.

**Comment by daveverwer** [comment]
That works great. Thank you James.

**Comment by Sherlouk** [comment]
Teamwork!

**Pull request closed without merging**
