### PR TITLE
Update recent views

### LINKED ISSUE #292: Add the version number of the latest release to the Recent Releases list on the home page.
Just make it a "Name - Version" inside the `<a>` tag.

### PR DESCRIPTION
**Pull request by finestructure**
- package summary in `recent_packages` view
- version in `recent_releases` view

Mainly for the RSS feeds but I've also just thrown in the small fix of adding the version to the Recent Releases section:

Screenshot 2020-06-07 at 12 31 25

Fixes #292

### CODE REVIEW

**Comment by finestructure** [comment]
Good to go!

**Comment by daveverwer** [comment]
I'm going to make a couple of commits to this locally to tweak the formatting of the version number. I think there's something I can do quickly to make it look better. Holding off on merging until then.

**Comment by finestructure** [comment]
Great! How about I split off this last commit and we merge the view updates separately?

**Comment by finestructure** [comment]
Never mind, it'd probably cause too much trouble with your copy of the branch

**Comment by daveverwer** [comment]
I think the change I'll make is tiny, probably fine to do it in this PR. Unless you have a strong preference for a different one.

**Pull request merged**
