### PR TITLE
Move `key` from metric name to label

### PR DESCRIPTION
**Pull request by finestructure**

### CODE REVIEW

**Review by Sherlouk — APPROVED** [review]
Makes total sense, and I'm glad that this still allows us to add new filters without having to update metrics

**Comment by Sherlouk** [comment]
I'm happy to merge this back into my branch if you're finished Sven?

**Comment by finestructure** [comment]
I'm done! And even with enums we wouldn't need to maintain it. It'd just have an initialiser from that type that takes the `rawValue`, no change required.

**Comment by daveverwer** [comment]
> I'm done!

I don't think James can merge PRs though 😬 I did it though!

**Comment by Sherlouk** [comment]
I technically can merge PRs, I just don't because you told me not to Dave 😂  (and I didn't know if Sven was going to make further tweaks)

**Comment by daveverwer** [comment]
Carry on then :) and certainly, if a PR is into your own branch you should feel free to merge that! 😅

**Pull request merged**
