### PR TITLE
Reduce processing frequency

### PR DESCRIPTION
**Pull request by finestructure**

### CODE REVIEW

**Comment by finestructure** [comment]
This has worked well - we're dipping to around 1200ish remaining requests per hour:

```
Sat 30 May 2020 09:09:46 CEST
rate.remaining: 1241
Sat 30 May 2020 09:10:46 CEST
rate.remaining: 1241
Sat 30 May 2020 09:11:47 CEST
rate.remaining: 1241
Sat 30 May 2020 09:12:47 CEST
rate.remaining: 5000
Sat 30 May 2020 09:13:48 CEST
rate.remaining: 4676
Sat 30 May 2020 09:14:48 CEST
rate.remaining: 4676
Sat 30 May 2020 09:15:49 CEST
rate.remaining: 4676

rate.remaining: 1581
Sat 30 May 2020 10:10:18 CEST
rate.remaining: 1581
Sat 30 May 2020 10:11:18 CEST
rate.remaining: 1263
Sat 30 May 2020 10:12:19 CEST
rate.remaining: 1263
Sat 30 May 2020 10:13:19 CEST
rate.remaining: 1263
Sat 30 May 2020 10:14:20 CEST
rate.remaining: 5000
Sat 30 May 2020 10:15:20 CEST
rate.remaining: 5000
Sat 30 May 2020 10:16:21 CEST
rate.remaining: 4682
Sat 30 May 2020 10:17:21 CEST
rate.remaining: 4682
Sat 30 May 2020 10:18:22 CEST
rate.remaining: 4682
Sat 30 May 2020 10:19:22 CEST

Sat 30 May 2020 11:13:51 CEST
rate.remaining: 1221
Sat 30 May 2020 11:14:51 CEST
rate.remaining: 1221
Sat 30 May 2020 11:15:52 CEST
rate.remaining: 1221
Sat 30 May 2020 11:16:52 CEST
rate.remaining: 1221
Sat 30 May 2020 11:17:53 CEST
rate.remaining: 4701
Sat 30 May 2020 11:18:54 CEST
rate.remaining: 4701
```

**Comment by finestructure** [comment]
Screenshot 2020-05-30 at 11 27 17

**Comment by daveverwer** [comment]
I'm glad that's not a chart from a machine hooked up to my heart 😂

**Comment by daveverwer** [comment]
The only thing I'd say here is that I think it's maybe worth considering making a GitHub request that returns with a rate limit error a hard error that alerts us in Rollbar. 

It shouldn't happen under normal circumstances, so it's something we should be notified about. Filed as #217

**Pull request merged**
