### PR TITLE
Blog link

### LINKED ISSUE #628: Add Blog link on the main site
In the header

### LINKED ISSUE #629: Launch blog post

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #628 
Fixes #629

⚠️ **DON'T MERGE UNTIL THE BLOG IS LIVE** ⚠️

### CODE REVIEW

**Comment by finestructure** [comment]
I've cherry-picked the blog link change over to #642 where I've prepared the other go-live HTML changes. That way we can push everything with a single PR and need to maintain just the one. I'll keep it rebased!

Ok to close this one in favour of #642?

**Comment by daveverwer** [comment]
I had planned to push the blog itself live as soon as the first post (not the build processing post) was live. I guess it doesn't matter much, but a few people might read the first post before next Friday?

**Comment by finestructure** [comment]
Ah, I see! No worries, I'll undo the cherry pick.

**Comment by daveverwer** [comment]
Deploying as 1.8.6

**Pull request merged**
