### PR TITLE
Xcbeautify GitHub actions format

### PR DESCRIPTION
**Pull request by finestructure**
WIP https://github.com/tuist/xcbeautify/issues/38#issuecomment-1667451590

### CODE REVIEW

**Comment by finestructure** [comment]
This is WIP for now, see the comment on the original PR above with respect to the output.

**Comment by daveverwer** [comment]
> This is WIP for now, see the comment on the original PR above with respect to the output.

Sorry. I completely missed that! 😬

**Comment by finestructure** [comment]
You didn't miss it, I hadn't finished that comment yet - just too fast 🙂

**Comment by finestructure** [comment]
Ok, this is actually a great change - I just completely missed where this shows up. It's on the action overview screen:

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/5782600018

CleanShot 2023-08-16 at 06 52 21@2x

and that entry is active and takes you to the test source.

CleanShot 2023-08-16 at 06 53 08@2x

**Comment by daveverwer** [comment]
> Ok, this is actually a great change - I just completely missed where this shows up. It's on the action overview screen:

Ohh, this is great 👍👍👍👍👍

**Pull request merged**
