### PR TITLE
Replace vapor-beta binaries with swift run

### PR DESCRIPTION
**Pull request by elfenlaid**
Not sure about this one, but the `vapor-beta` command seems like a left-over or at least doesn't work anymore

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]
Yes! This is a blast from the past.

**Review by finestructure — APPROVED** [review]

**Comment by finestructure** [comment]
Closing and re-opening to make the tests run

**Comment by finestructure** [comment]
Mmmm, CI is not triggering and I guess it's because it's not a branch in the SPI repo. I'll push the branch up into SPI, that should sort it and we should be able to switch over the PR seamlessly 🤞

**Comment by finestructure** [comment]
Superseded by #1124

**Comment by daveverwer** [comment]
I also just invited you to have write access to the project @elfenlaid. The `main` branch is protected, but you should be able to create new branches and make PRs on those with CI enabled now.

**Pull request closed without merging**
