### PR TITLE
Clean up and upstream changes to Plot

### PR DESCRIPTION
**Pull request by daveverwer**
Cleaned up all of the Plot code so we're no longer using any `attribute` or `element` calls directly. Upstreamed whatever made sense to Plot:

* [Boolean attributes · Pull Request #68](https://github.com/JohnSundell/Plot/pull/68)
* [Added an attribute to represent the button types · Pull Request #69](https://github.com/JohnSundell/Plot/pull/69)
* [Added a global `spellcheck` attribute and tests with common use cases · Pull Request #70](https://github.com/JohnSundell/Plot/pull/70)
* [Made the `title` attribute into a global attribute · Pull Request #71](https://github.com/JohnSundell/Plot/pull/71)

After those are merged and a release is done, we can remove all of the temporary code in `Plot+Extensions.swift`. This is worth merging on its own though.

⚠️ Needs testing on staging before deploying to production ⚠️

### CODE REVIEW

**Comment by daveverwer** [comment]
The diffs in 821e57593d1d06373c5befb74152b6320844facc are what's truly important here.

**Comment by finestructure** [comment]
Mmm, I don't see a change to `Package.resolved` - if the changes were upstreamed shouldn't we move to a new Plot revision? I don't see a merge in Plot either. The latest (untagged) change is your `description` PR in revision `574b1ae2ffc45beeb95d56fe5df91e493d42c1b9` 🤔

**Comment by finestructure** [comment]
Right, these are all still open PRs. How does our CI not break though?

**Comment by finestructure** [comment]
Right, I see. All the anticipated upstream changes are in `Plot+Extensions.swift` _until_ they're upstreamed :+1:

**Review by finestructure — APPROVED** [review]

**Pull request merged**
