### PR TITLE
Add Build.logUrl field

### PR DESCRIPTION
**Pull request by finestructure**
In preparation to send the build logs from the builders.

NB: schema change, should deploy as 1.4.0

### CODE REVIEW

**Comment by daveverwer** [comment]
So the log itself goes into the (existing) `logs` field? Is this for the URL to the GitLab log?

**Comment by finestructure** [comment]
Yes, or any queueing system or storage system we intend to support/use instead perhaps. The idea is that we store a limited log in `logs` and a reference to the complete logs in `log_url`.

An alternative would be to just make `logs` accept a structured `json`, like so:

```
{
“logs”: “...”,
“url”: “...”
}
```

I can’t really decide which I like better tbh. But I’m pretty sure we’ll want to keep a reference to the Gitlab pipelines somewhere.

**Comment by daveverwer** [comment]
I think for a large text field I'd much rather just have that in a standard `text` type field.

Sounds good! Merging now and I'll watch it through to staging then deploy to prod if all goes well.

**Comment by daveverwer** [comment]
Seems like something is failing repeatedly while deploying to staging:

https://gitlab.com/finestructure/swiftpackageindex-dev/-/jobs/634786986

Starting at about line 70, it can't find a manifest.

**Comment by finestructure** [comment]
Yeah, it‘s waiting on the prod project building. I‘ll give it a prod - heh.

**Comment by finestructure** [comment]
Retry worked and it‘s deployed now

**Pull request merged**
