### PR TITLE
Reset funding links data

### LINKED ISSUE #2850: Funding link related crash
We've seen repeated crashes of the server, forcing a roll-back to 2.97.16. There were warnings like

```
[ WARNING ] invalid field: 'funding_links', type: Array<FundingLink>, error: Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [SomeCodingKey(stringValue: "repositories_funding_links (10)", intValue: nil)], debugDescription: "Unable to interpret value of PSQL type JSONB[]: ByteBuffer { readerIndex: 0, writerIndex: 240, readableBytes: 240, capacity: 240, storageCapacity: 32768, slice: _ByteBufferSlice { 1616..<1856 }, storage: 0x00007f7ab43c04a0 (32768 bytes) }", underlyingError: nil)) [component: server]
```

near the crashes in the logs, which might be related or causing the issue.

### PR DESCRIPTION
**Pull request by finestructure**
Fixes #2850

### CODE REVIEW

**Comment by finestructure** [comment]
Setting to auto-deploy to staging, which will allow us to confirm it's working before we deploy to prod.

**Review by daveverwer — APPROVED** [review]

**Comment by finestructure** [comment]
For some reason the migration was not applied on staging. I'll try to run in manually.

**Comment by finestructure** [comment]
Ok, c429325c2058c10683e8e92f4486466c32f63206 never got deployed for some reason.

**Comment by finestructure** [comment]
Deployment had failed because the build on prod took too long https://gitlab.com/finestructure/swiftpackageindex-dev/-/jobs/5966093781. All sorted now.

**Pull request merged**
