### PR TITLE
Diff against main to determine if Percy needs to run

### LINKED ISSUE #1725: Snapshots workflow doesn't run when pushing multiple changes at once
From https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/1723#issuecomment-1116717189

> Actually I wonder if it's because you pushed up multiple commits at once. I think our current command expects you push every commit up. At the moment it's comparing the last commit, to the commit before it, and there is no changes to HTML files in that last commit.

You're right, this is the problem. I'm not sure there's going to be an easy way to check how many commits there have been between the current push and the previous push so I think the best way will be to go back to our fallback plan of diffing against `main`. For me, pushing multiple commits up is something I do *all* the time.

If the diff between a branch and main contains any of the files or patterns we're checking for, Percy runs. It will mean that every push to a branch after a single HTML change will run Percy, but it will work in every case.

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #1725

### CODE REVIEW

**Review by finestructure — APPROVED** [review]

**Comment by daveverwer** [comment]
Hmm. I tested this locally and it worked well, but the workflow apparently found changes when running in CI.

If I have this branch checked out and run:

```
git diff origin/main --shortstat "**.html" "**.scss" "**.js" ".percy.yml" ".github/workflows/snapshots.yml"
```

I get no output, which is correct.

**Comment by daveverwer** [comment]
> I get no output, which is correct.

Wait. Ignore me. I got no output before I also changed the workflow file which is included in that command! All working as expected!

**Comment by Sherlouk** [comment]
Isn't this what the script was initially, but run into issues when run on `main`?

**Comment by daveverwer** [comment]
If I remember rightly, it wasn't due to a problem. It was more that we could save some Percy quota with the other version.

**Comment by daveverwer** [comment]
and reduce the fetch depth, too.

**Comment by daveverwer** [comment]
But if there's a better way to do it. I'm all ears!

I don't know how we'd check how many commits were just pushed, though.

**Comment by Sherlouk** [comment]
Probably doesn't need to be a completely different workflow, just change that one script based on the current ref?

**Pull request merged**
