### PR TITLE
Show readme

### PR DESCRIPTION
**Pull request by finestructure**
Largely unstyled display of Markdown-rendered README.

- use `?readme=0` to switch it off
- gated to show only on `development` env either way

Screenshot 2020-11-12 at 12 45 11

Our H1 displays smaller that our H2, I think, which makes the titles look a bit weird right now.

Speed seems fine running it via my coworking network connection.

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]
> Our H1 displays smaller that our H2, I think, which makes the titles look a bit weird right now.

Yea, when we roll this out we'll have a `readme.scss` at the same time to namespace some rules for styling inside the readme. There will be lots of edge cases too!

This looks great 👍 but, I'm not sure it "Fixes" #410 yet as I'd like to merge this without marking that as closed. It needs styling, not gating to staging, etc... I'll merge this now and then re-open that issue.

**Comment by finestructure** [comment]
Part of #410

**Comment by Sherlouk** [comment]
Will it take some time for the URLs to get updated after changed to raw/download URL? Package below isn't rendering correctly just yet but might be queued for an update!

https://staging.swiftpackageindex.com/sindresorhus/CircularProgress
https://raw.githubusercontent.com/sindresorhus/CircularProgress/master/readme.md

image

**Comment by finestructure** [comment]
Well spotted, that's probably an issue with the Markdown renderer. We probably need to use one that's fully CommonMark compliant. If the url wasn't updated it'd show raw html instead (and the recent packages will definitely be updated as well).

**Comment by Sherlouk** [comment]
Interesting point yeah - I suppose we need to take into account the "GitHub Flavoured" version too (not sure what the delta is between CommonMark and GitHub's version though)

**Comment by daveverwer** [comment]
> We probably need to use one that's fully CommonMark compliant. 

If only there was a website where we could search all available Swift packages to see if there was a CommonMark compatible package. Maybe it could also show how well maintained it was, and possibly even show the READM.... Wait... 😂

**Comment by daveverwer** [comment]
In all seriousness though, I don't see one which supports GitHub Flavoured Markdown in the index. There are several that wrap cmark though.

**Comment by Sherlouk** [comment]
I know Ryan Nystrom started working on a GitHub Flavoured package for GitHawk but not sure it had 100% coverage either 🤔 

I think he mentioned their new app uses HTML for rendering it in the main GitHub so might be worth reaching out and seeing if he can point you in a good direction?

**Comment by daveverwer** [comment]
Yea I found that. It's a couple of years out of date, doesn't support SPM yet, and is marked as WIP. But if we decide we do need to support GFM, that's where we'll start.

https://github.com/GitHawkApp/cmark-gfm-swift

**Pull request merged**
