### PR TITLE
SPI-Indexing 11

### PR DESCRIPTION
**Pull request by finestructure**

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]

**Comment by Sherlouk** [comment]
I'm sure there's a reason we're not, but could we use the Twitter API for this? 👀

**Comment by daveverwer** [comment]
> I'm sure there's a reason we're not

We could do this PR for 500 episodes before it'd be more efficient to automate. 😂

**Comment by Sherlouk** [comment]
> We could do this PR for 500 episodes before it'd be more efficient to automate. 😂

B-but what if we had a page where you can see all of the past episodes!?

and what if it had all these amazing magical podcast features!? 😂

Worth opening an issue if someone feels like it? Feels like a relatively easy piece 😊

**Comment by daveverwer** [comment]
> B-but what if we had a page where you can see all of the past episodes!?

https://blog.swiftpackageindex.com

> and what if it had all these amazing magical podcast features!? 😂

I too have a list of improvements for Twitter Spaces 😂

**Pull request merged**
