### PR TITLE
Prevent empty strings from being shown as homepage URLs

### LINKED ISSUE #1716: Package homepage buttons are showing for packages without a homepage set
For example, on: https://swiftpackageindex.com/mxcl/PromiseKit

Screenshot 2022-04-26 at 16 39 03@2x

I think this is a `NULL`/`EMPTY` string issue. For example, looking at Max's packages:

Screenshot 2022-04-26 at 16 41 14@2x

PromiseKit and [AppUpdater](https://swiftpackageindex.com/mxcl/AppUpdater) have the button, but [StreamReader](https://swiftpackageindex.com/mxcl/StreamReader) doesn't.

### PR DESCRIPTION
**Pull request by Sherlouk**
Fixes #1716

### CODE REVIEW

**Comment by Sherlouk** [comment]
one mo

**Comment by daveverwer** [comment]
Thanks James! Even testing our other untested functions! 🙇

**Comment by Sherlouk** [comment]
they were plenty tested implicitly by other tests but might as well cover the 3 extensions in that grouping while I was there 😛

**Comment by daveverwer** [comment]
I can't see it possibly being related to anything in this PR. That check also failed with #1717, I noticed. Something we need to look at.

**Comment by finestructure** [comment]
The query performance tests is partly dependent on the db and its content. Costs can change depending on how effective indexes are or which choices the planner makes depending on table statistics.

I'll merge this now and add an issue to follow up on query performance.

**Comment by finestructure** [comment]
#1721

**Pull request merged**
