### PR TITLE
Update display string to Xcode 12.2

### LINKED ISSUE #679: Update Swift 5.3 builds to Xcode 12.2
I believe Xcode 12.2 is the version we are waiting for.

- install on
  - [x] dev
  - [x] prod
  - [x] dtk
  - [x] ceres
- update builder
  - [x] determine matching Linux version
  - [x] update `SwiftVersion.xcodeVersion`
  - [x] update `SwiftVersion.dockerImage`
  - run test builds on all builders
    - [x] dev
    - [x] prod
    - [x] dtk
    - [x] ceres
  - [x] merge https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/41
- update server
  - [x] update Xcode version string in `SwiftVersion+Build.swift:25`
  - [x] merge https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/768
- delete 5.3 builds (in batches, to control for build volume)
  - [x] write select/delete query
  - [ ] run deletions
- remove old Xcode 12 betas
  - [x] Ceres
  - [x] DTK
  - [x] dev
  - [x] prod

Edit: review/update todos

### PR DESCRIPTION
**Pull request by finestructure**
⚠️ Merge after builders have been updated: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/41

Fixes #679

### CODE REVIEW

**Comment by finestructure** [comment]
I have depoyed the builder using 12.2rc for the 5.3 builds, so we can merge and deploy this now.

**Comment by finestructure** [comment]
Back to draft - just realised we'll want to drop the "beta" label on Swift 5.3

**Comment by daveverwer** [comment]
I think we should drop both the (latest) and the (beta) labels from the Swift versions. (latest) is only really useful when there is a version in beta.

**Comment by finestructure** [comment]
Fixed:

Screenshot 2020-11-06 at 16 22 42

**Comment by finestructure** [comment]
Good to go now

**Review by daveverwer — APPROVED** [review]

**Pull request merged**
