### PR TITLE
New snapshots generated on M1

### PR DESCRIPTION
**Pull request by daveverwer**
Hopefully this'll put us both back in sync! 🤞

### CODE REVIEW

**Comment by finestructure** [comment]
😞 

CleanShot 2021-11-04 at 14 41 52@2x

**Comment by finestructure** [comment]
Some are green now though. I don't think we've had that before:

CleanShot 2021-11-04 at 14 46 39@2x

Must be the ones where only the banner had an svg on it.

**Review by finestructure — APPROVED** [review]

**Comment by daveverwer** [comment]
How frustrating. Did you do a `make build-front-end` first to make sure you're all up to date with css?

**Comment by finestructure** [comment]
ah no, I did not! Let me try that. That might actually be the problem.

**Pull request merged**
