### PR TITLE
Package update

### PR DESCRIPTION
**Pull request by finestructure**

### CODE REVIEW

**Review by daveverwer — APPROVED** [review]

**Comment by finestructure** [comment]
CleanShot 2021-02-16 at 10 16 11@2x

**Comment by daveverwer** [comment]
What? How is this failing now when it passed as this was integrated?

**Comment by daveverwer** [comment]
Ohh, did a vapor update kill something in it?

**Comment by finestructure** [comment]
No, I think it's aliasing, due to OS version or even architecture. I think this is the first time I've run the test after merge:

CleanShot 2021-02-16 at 10 27 23@2x

**Comment by finestructure** [comment]
Yep, fails on `main` for me as well. I'm on macOS 11.2.1 (20D74), Xcode 12.4 (12D4e). Did you record with the same versions? It'd be curious if those don't line up. Normally that only happens when OS or Xcode versions change.

**Comment by finestructure** [comment]
> What? How is this failing now when it passed as this was integrated?

The snapshots aren't being run on CI, because WKWebView is not available on Linux.

**Comment by finestructure** [comment]
I'll go ahead and merge this as it's not a regression (but we'll want to figure out why we're getting different snapshot test results separately)

**Comment by daveverwer** [comment]
> > What? How is this failing now when it passed as this was integrated?
> 
> The snapshots aren't being run on CI, because WKWebView is not available on Linux.
> 
> Edit: the image snapshots, that is

I knew that, but sometimes I don't think 😂

**Comment by daveverwer** [comment]
> Yep, fails on `main` for me as well. I'm on macOS 11.2.1 (20D74), Xcode 12.4 (12D4e). Did you record with the same versions? It'd be curious if those don't line up. Normally that only happens when OS or Xcode versions change.

All just passed for me with:

* Safari 14.0.3 (16610.4.3.1.4)
* Xcode 12.4 (12D4e)
* macOS 11.2.1 (20D74)

**Comment by daveverwer** [comment]
Strange that our versions of macOS are different. Is that an M1 specific version?

**Comment by finestructure** [comment]
Different? Isn't it exactly the same?

**Comment by daveverwer** [comment]
> Different? Isn't it exactly the same?

You snuck in before I was able to delete my comment. I was mixing up the Xcode build number with the macOS build number at first.

**Pull request merged**
